# Generated by Django 5.0.1 on 2024-03-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coverImg',
            field=models.FileField(blank=True, default='cover.png', null=True, upload_to='cover/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profileImg',
            field=models.FileField(default='profile.jpeg', upload_to='profileImg/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
